[package]
name = "substrate-crypto-light"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2b_simd = {version = "1.0.2", default-features = false}
hmac = "0.12.1"
lazy_static = {version = "1.4.0", default-features = false, features = ["spin_no_std"]}
parity-scale-codec = {version = "3.6.9", default-features = false}
pbkdf2 = {version = "0.11.0", default-features = false}
rand_core = {version = "0.6.4", default-features = false}
regex = {version = "1.10.3", default-features = false}
schnorrkel = {version = "0.10.2", default-features = false, features = ["u64_backend"]}
sha2 = {version = "0.10.6", default-features = false}
spki = {version = "0.6.0", features = ["alloc"]}
zeroize = "1.5.7"


[dev-dependencies]
sp-core = {version = "30.0.0"}

[features]
default = ["std"]
std = []
